name: "score_model"
backend: "python"
max_batch_size: 0

input [
  {
    name: "INPUT"
    data_type: TYPE_FP64
    dims: [ 8 ]
  }
]

output [
  {
    name: "OUTPUT"
    data_type: TYPE_FP64
    dims: [ 3 ]
  }
]

instance_group [
  {
    kind: KIND_CPU
  }
]